### ISSUE TITLE
Delete with `D`

### ISSUE THREAD

**Issue by usagi-flow** [etienne-k/helix#115]
In normal mode, `D` should delete until the end of the line.
In visual mode, the entire line should be deleted.
In visual line mode, all selected lines should be deleted.

The implementation of this should be pretty minimal and straightforward, although the edge cases with the visual mode (and as usual, the last `~` line, which doesn't exist as such in Vim) should be paid attention to.

**Comment by mat63vitus** [comment]
For the time it is being implemented, there is a hacky way I achieve this (thought might as well share with others)

Add this to `config.toml`

```toml
[keys.normal]
S-d = ["evil_characterwise_select_mode", "goto_line_end", "evil_delete"]

[keys.select]
S-d = "evil_delete"
```
