### ISSUE TITLE
Line selection mode

### ISSUE THREAD

**Issue by antoyo** [etienne-k/helix#17]
Hi.
It would be nice to have a line-selection (`V-LINE`) mode like in vim with `V`.
Thanks.

**Comment by mike-lloyd03** [comment]
For now, I'm using this:

```toml
[keys.normal]
"V" = ["select_mode", "extend_to_line_bounds"]
```
